config:
  build_jobs: 20
  install_tree:
    projections:
      all: ${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH:6}
    root: /appl/spack/v016/install-tree
  build_stage: /local_scratch/build/spack-stage
  module_roots:
    lmod: /appl/spack/v016/modulefiles
  source_cache: /appl/spack/v016/sources
